tests: Add example code for #37, have to re-open since it does not work
This tests currently runs into an endless recursion as follows:

  java.lang.OutOfMemoryError: Java heap space
	at dev.flang.ast.AbstractType.actualTypes(AbstractType.java:484)
	at dev.flang.ast.AbstractType.actualType_(AbstractType.java:710)
	at dev.flang.ast.AbstractType.actualType(AbstractType.java:660)
	at dev.flang.ast.AbstractType.actualType_(AbstractType.java:711)
	at dev.flang.ast.AbstractType.actualType(AbstractType.java:660)
	at dev.flang.ast.AbstractType.actualTypes(AbstractType.java:479)
	at dev.flang.ast.AbstractType.actualType_(AbstractType.java:710)