jvm: add FuzionOptions to jar file when using `-jar` target
Otherwise, I see this

     > make run_tests_jar
    rm -rf build/tests
    mkdir -p build
    cp -rf ./tests build/tests
    chmod +x build/tests/*.sh
    Exception in thread "Fuzion thread" java.lang.NoClassDefFoundError: dev/flang/util/FuzionOptions
    	at dev.flang.util.Errors.<clinit>(Errors.java:63)
    	at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:116)
	at java.base/java.lang.Thread.run(Thread.java:1583)
    Caused by: java.lang.ClassNotFoundException: dev.flang.util.FuzionOptions