ast: fix null pointer exception
reproduce via:
fz tests/mod_http_message/http_message_test.fz
```
java.lang.NullPointerException: Cannot invoke "dev.flang.ast.AbstractType.visit(dev.flang.ast.FeatureVisitor, dev.flang.ast.AbstractFeature)" because "this._type" is null
        at dev.flang.ast.FunctionReturnType.visit(FunctionReturnType.java:138)
        at dev.flang.ast.Feature.visit(Feature.java:1324)
        at dev.flang.ast.Feature.internalResolveTypes(Feature.java:1627)
        at dev.flang.ast.Resolution.resolveTypes(Resolution.java:505)
        at dev.flang.ast.Feature.resultTypeIfPresentUrgent(Feature.java:2455)
        at dev.flang.ast.Call.getActualResultType(Call.java:1401)
        at dev.flang.ast.Call.setActualResultType(Call.java:2732)
        at dev.flang.ast.Call.resolveTypes0(Call.java:2616)
        at dev.flang.ast.Call.resolveTypes(Call.java:2569)
```