air: in assignment, propagate clazz from unused field to expression, improves #173
The propagated field's resut clazz is required by the C backend for boxing, even
if the resulting boxed value is thrown away.

This fixes only part of the C backend to compile idiom8ex.fz, now the result is

  java.lang.Error: Clazz.fieldIndex() did not find field ref map<string, i32>.keys.ref res.asStream.ref @52531.call.@53126